linters-settings:
  govet:
    check-shadowing: false
    enable:
      - assign
      - atomic
      - atomicalign
      - bools
      - copylocks
      - deepequalerrors
      - errorsas
      - fieldalignment
      - findcall
      - httpresponse
      - ifaceassert
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - printf
      - shift
      - sortslice
      - stdmethods
      - stringintconv
      - structtag
      - testinggoroutine
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
      - unusedwrite

  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  varnamelen:
    min-name-length: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  nolintlint:
    require-specific: true

linters:
  disable-all: true
  enable:
    # default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # additional
    - bidichk
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - goimports
    - gofmt
    - gomnd
    - gosec
    - ifshort
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
