name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build server
        run: go build -v ./cmd/http/main.go

      - name: Build cli
        run: go build -v ./cmd/cli/main.go

      - name: Test everything
        run: go test -v ./...
